import React from 'react'
import {useState} from "react"
import Tasks from "../components/Tasks"
import Title from "../components/Title"
import AddTaskForm from "../components/AddTaskForm"
import TasksList from '../components/TasksList'

const ToDoViewPpal = () => {
  
  const MOCK =[
    {id:1,
    title: 'Tarea 1'},
  ]

  //List of Tasks
  const [listaDeTareas,setListaDeTareas] = useState(MOCK);

  const newTaskToDo = (tareaAAgregar) => ({
    id: window.crypto.randomUUID(), //ID autogenerated
    title: tareaAAgregar,
    })

  //Agrgar Tarea onSubmit
  const addTask = (p) => {
    console.log(p);
    const agregarTarea = newTaskToDo(p.nameNewTask);
    console.log(agregarTarea);
    setListaDeTareas([...listaDeTareas,agregarTarea]);
  }

  return (
    <div>
        <Title><h1>To Do List</h1></Title>
        <Title><h4>Agregá una nueva tarea</h4></Title>
       
        <section>
            <AddTaskForm 
                onSubmitted ={
                  (loQueRecibo) => {addTask(loQueRecibo)}
                } />
        </section>
        <section>
          {listaDeTareas.map((e) => (
           <Tasks key={e.id} tarea={e.title} />
            ))}
         </section>
    </div>
  )
}

export default ToDoViewPpal
