import React from 'react'
import {useState} from "react"
import Tasks from "../components/Tasks"
import Title from "../components/Title"
import AddTaskForm from "../components/AddTaskForm"

const ToDoViewPpal = () => {
  
  //List of Tasks
  const [listaDeTareas,setListaDeTareas] = useState([]);

  const newTaskToDo = (tituloTarea) => ({
    id: window.crypto.randomUUID(), //ID autogenerated
    title: tituloTarea,
    })

  //Agrgar Tarea onSubmit
  const addTask = (tareaNueva) => {
    const agregarTarea = newTaskToDo(tareaNueva);
    setListaDeTareas([...listaDeTareas,agregarTarea]);
  }

  return (
    <div>
        <Title><h1>To Do List</h1></Title>
        <Title><h4>Agregá una nueva tarea</h4></Title>
       
        <section>
            <AddTaskForm 
                onSubmitted ={
                  (newTask) => {addTask(newTask)}
                } />
        </section>
        <section>
            {listaDeTareas.map((e) => (
                <Tasks key={e.id} tarea={e.title} />
    ))}
            </section>
    </div>
  )
}

export default ToDoViewPpal
