import React from 'react'
import {useState} from "react"
import Tasks from "../components/Tasks"
import Title from "../components/Title"
import AddTaskForm from "../components/AddTaskForm"

const MOCK_TAREAS = [
    {
        id: 1,
        title: 'Tarea 1',
        completed: false,
    },
    {
        id: 2,
        title: 'Tarea 2',
        completed: true,
    },

]
const ToDoViewPpal = () => {
  
  //List of Tasks
  const [listaDeTareas,setListaDeTareas] = useState(MOCK_TAREAS);

   //Form Entry New Task
   const [newTask,setNewTask] = useState({nameNewTask: ""});

   //Captura de nueva Tarea
   const handleChange = (e) => {
    //desestructura el evento y captura la entrada de datos
    const {name,value} = e.target;
    setNewTask({
        ...newTask,
        [name]: value
    });
  };

  //Nuevas Tareas
  //1- Creacion de Tarea Nueva
  const newTaskToDo = (tituloTarea) => ({
    id: window.crypto.randomUUID(), //ID autogenerated
    title: tituloTarea,
    completed: false,
    })

    //2-limpieza del formulario
    const resetForm = () => setNewTask({nameNewTask: ""});

    //Agregado de Tarea Nueva al listado de tareas
    const handleSubmit = (e) => {
    e.preventDefault();
    //Agrgar Tarea onSubmit
    const agregarTarea = newTaskToDo(newTask.nameNewTask);
    setListaDeTareas([...listaDeTareas,agregarTarea]);
    //limpieza del formulario
    resetForm();
    };
 

  return (
    <div>
        <section>
            <Title />
        </section>
        <section>
            <AddTaskForm 
                tarea={newTask.nameNewTask}
                captura={handleChange}
                agregar={handleSubmit} />
        </section>
        <section>
            {listaDeTareas.map((e) => {
                return (
                    <Tasks key={e.id}
                          tarea={e.title}
                          estado={e.completed} />
                    );
            })}
        </section>
    </div>
  )
}

export default ToDoViewPpal
