import React from "react";
import { useState, useEffect } from "react";
import {v4 as uuidv4 } from 'uuid';

//Planilla de tareas es un componente padre.
//Lista las tareas y actualiza el estado.
const PlanillaDeTareas = ({ loQueEnvio }) => {
  //const text = console.log(`Hola ${onListed}`);
  const DATOS_MOCK = [
    { id: 1, title: "Tarea 1", editable: false},
    { id: 2, title: "Tarea 2", editable: false},
  ];

  //useState actualizacion de tareas
  const [listaDeTareas, setListaDeTareas] = useState(DATOS_MOCK);

  useEffect(() => {
    // Esta función se ejecutará cuando loQueEnvio cambie
    if (loQueEnvio) {
      const nuevaTarea = {
        id: window.crypto.randomUUID(), //ID autogenerated,
        title: loQueEnvio,
        editable: false,
      };
      // Usamos la función de actualización para asegurarnos de que el estado se actualice correctamente.
      setListaDeTareas((prevTareas) => [...prevTareas, nuevaTarea]);
    }
  }, [loQueEnvio]);
  const handleEdit = (taskId) => {
    // Cambiar el estado de editable a true para habilitar la edición de la tarea
    setListaDeTareas((prevTareas) =>
      prevTareas.map((tarea) =>
        tarea.id === taskId ? { ...tarea, editable:true} : tarea
      )
    );
  };

  const handleGuardarEdit = (taskId) => {
    // Cambiar el estado de editable a true para habilitar la edición de la tarea
    setListaDeTareas((prevTareas) =>
      prevTareas.map((tarea) =>
        tarea.id === taskId ? { ...tarea, editable: false } : tarea
      )
    );
  };

  const handleCompletar = (taskId) => {
    // Cambiar el estado de editable a false para cancelar la edición de la tarea
    setListaDeTareas((prevTareas) =>
      prevTareas.filter((tarea) =>
        tarea.id !== taskId)
    );
  };

  return (
    <div>
      {listaDeTareas.map((tarea) => (
        <div key={tarea.id}>
          {tarea.editable ? (
            // Si la tarea es editable, muestra un campo de entrada para la edición
            <input
              type="text"
              value={tarea.title}
              onChange={(e) => {
                // Actualizar el título de la tarea mientras se edita
                setListaDeTareas((prevTareas) =>
                  prevTareas.map((t) =>
                    t.id === tarea.id ? { ...t, title: e.target.value } : t
                  )
                );
              }}
            /> //ciero input
          ) : (
            // Si la tarea no es editable, muestra el título de la tarea
            tarea.title
          )}
         {tarea.editable ? (<button onClick={() => handleGuardarEdit(tarea.id)}>Guardar Edit</button>) :(<button onClick={() => handleEdit(tarea.id)}>Editar</button>)}
         <button onClick={() => handleCompletar(tarea.id)}>Tarea Completada</button>
        </div>
      ))}
    </div>
  );
};

export default PlanillaDeTareas;
