import { useState, useEffect } from "react";
import {v4 as uuidv4 } from 'uuid';

//Planilla de tareas es un componente padre.
//Lista las tareas y actualiza el estado.
const PlanillaDeTareas = ({ loQueEnvio }) => {

  //useState actualizacion de tareas
  const [listaDeTareas, setListaDeTareas] = useState([]);

  useEffect(() => {
    // Esta función se ejecutará cuando loQueEnvio cambie
    if (loQueEnvio) {
      const nuevaTarea = {
        id: uuidv4(), //ID autogenerated,
        title: loQueEnvio,
        editable: false,
      };
      // Usamos la función de actualización para asegurarnos de que el estado se actualice correctamente.
      setListaDeTareas((prevTareas) => [...prevTareas, nuevaTarea]);
    }
  }, [loQueEnvio]);
  
  const handleEdit = (taskId) => {
    // Cambiar el estado de editable a true para habilitar la edición de la tarea
    setListaDeTareas((prevTareas) =>
      prevTareas.map((tarea) =>
        tarea.id === taskId ? { ...tarea, editable:true} : tarea
      )
    );
  };

  const handleGuardarEdit = (taskId) => {
    // Cambiar el estado de editable a true para habilitar la edición de la tarea
    setListaDeTareas((prevTareas) =>
      prevTareas.map((tarea) =>
        tarea.id === taskId ? { ...tarea, editable: false } : tarea
      )
    );
  };

  const handleCompletar = (taskId) => {
    // Cambiar el estado de editable a false para cancelar la edición de la tarea
    setListaDeTareas((prevTareas) =>
      prevTareas.filter((tarea) =>
        tarea.id !== taskId)
    );
  };

  return (
    <div>
      {listaDeTareas.length > 0 ? (
        listaDeTareas.map((tarea) => (
          <div key={tarea.id}>
            {tarea.editable ? (
              <input
                type="text"
                value={tarea.title}
                onChange={(e) => {
                  setListaDeTareas((prevTareas) =>
                    prevTareas.map((t) =>
                      t.id === tarea.id ? { ...t, title: e.target.value } : t
                    )
                  );
                }}
              />
            ) : (
              tarea.title
            )}
            {tarea.editable ? (
              <button onClick={() => handleGuardarEdit(tarea.id)}>Guardar Edit</button>
            ) : (
              <button onClick={() => handleEdit(tarea.id)}>Editar</button>
            )}
            <button onClick={() => handleCompletar(tarea.id)}>Tarea Completada</button>
          </div>
        ))
      ) : (
        <p>NO HAY TAREAS</p>
      )}
    </div>
  );
};

export default PlanillaDeTareas;
