import { useState, useEffect } from "react";
import {v4 as uuidv4 } from 'uuid';

//Planilla de tareas es un componente padre.
//Lista las tareas y actualiza el estado.
const PlanillaDeTareas = ({ loQueEnvio }) => {

  //useState actualizacion de tareas
  const [listaDeTareas, setListaDeTareas] = useState([]);

  useEffect(() => {
    // Esta función se ejecutará cuando loQueEnvio cambie
    if (loQueEnvio) {
      const nuevaTarea = {
        id: uuidv4(), //ID autogenerated,
        title: loQueEnvio,
        editable: false,
        completed: false,
      };
    // Actualizo el estado con  la nueva tarea
    setListaDeTareas((prevTareas) => [...prevTareas, nuevaTarea]);
    }
  }, [loQueEnvio]);

  const handleEdit = (taskId) => {
    //Cambia una propiedad del Estado "editable"
    const draft = structuredClone(listaDeTareas);
      const tareaAEditar = draft.find((te)=> te.id === taskId);
      tareaAEditar.editable = true;
      setListaDeTareas(draft);  
  };

  const handleGuardarEdit = (taskId) => {
    //Cambia una propiedad del Estado "editable"
    const draft = structuredClone(listaDeTareas);
      const tareaAGuardarEdit = draft.find((tge)=> tge.id === taskId);
      tareaAGuardarEdit.editable = false;
      setListaDeTareas(draft);  
  };

  const handleBorrar = (taskId) => {
    const draft = listaDeTareas.filter((t) => t.id !== taskId);
    console.log(draft);
    setListaDeTareas(draft);
  };

  const handleCompletarTarea = (taskId) => {
  //Cambia una propiedad del Estado de Completo/incompleto de una tarea sin mutar el estado original
    const draft = structuredClone(listaDeTareas);
    const tareaACambiar = draft.find((tc)=> tc.id === taskId);
    tareaACambiar.completed = !tareaACambiar.completed;
    setListaDeTareas(draft);  
  }

  return (
    <div>
      {listaDeTareas.length > 0 ? (
        listaDeTareas.map((tarea) => (
          <div key={tarea.id}>
            {tarea.editable ? (
              <input
                type="text"
                value={tarea.title}
                /*onChange={(e) => {
                  /*setListaDeTareas((prevTareas) =>
                    prevTareas.map((t) =>
                      t.id === tarea.id ? { ...t, title: e.target.value } : t
                    )
                  );
                }}*/
                onChange={(e) => {
                  //Cambia una propiedad del Estado "title"
                  const draft = structuredClone(listaDeTareas);
                  const textoAEditar = draft.find((tae)=> tae.id === tarea.id);
                  textoAEditar.title = e.target.value;
                  setListaDeTareas(draft);
                }}
              />
            ) : (
              <span><b>{tarea.title}</b>
                    <span style={{color: 'blue'}}><b>    ----     ----    </b></span>
                    <span>{tarea.completed ? 
                      (<span style={{color:'green'}}>completa</span>):
                      (<span style={{color:'red'}}>incompleta</span>)}
                    </span>
              </span>
            )}
            {tarea.editable ? (
              <button onClick={() => handleGuardarEdit(tarea.id)}>Guardar Edit</button>
            ) : (
              <button onClick={() => handleEdit(tarea.id)}>Editar</button>
            )}
            <button onClick={() => handleCompletarTarea(tarea.id)}>Completar Tarea</button>
            <button onClick={() => handleBorrar(tarea.id)}>Borrar Tarea</button>
          </div>
        ))
      ) : (
        <p>NO HAY TAREAS</p>
      )}
    </div>
  );
};

export default PlanillaDeTareas;
